### ISSUE TITLE
Any chance of a solid color variant?

### ISSUE THREAD

**Issue by pierre-rs** [ad-on-is/Tokyo-Darker#2]
Hi,

First, great job! Your Tokyo-Darker theme is awesome!

Is there any way to remove transparency (from GTK apps, right click context menus, Gnome Shell's top panel bar and etc) and get only solid color on the Tokyo-Darker theme?

Thanks!

**Comment by ad-on-is** [comment]
Not anytime soon. Since I frequently make minor changes to the theme to my likings, I'd have to maintain multiple versions. And I' don't have the time for that right now.

 I added transparency ever so slightly in the hope that GNOME might add blur to mutter-wm in future.

**Comment by pierre-rs** [comment]
Ok, thanks! 
Yes, if Gnome enabled the ability to have blur it would be really cool!
